version: 2
jobs:
  build:
    working_directory: ~/project # this entire string is the value of the env var $CIRCLE_WORKING_DIRECTORY
    docker:
      - image: circleci/node:7.10.0-browsers
      # Environment variable for all commands executed in the primary container
        environment:
          NODE_ENV: test
          CI: yes
    steps:
      - checkout
      - run:
          name: npm-install-global
          command: sudo npm install -g codeclimate-test-reporter
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Install Chromedriver latest version
          command: |
            sudo apt-get update
            sudo apt-get install lsb-release
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
      - run:
          name: run-clean-all
          command: npm run clean:all
      - run:
          name: run-install-demo-systemjs
          command: cd demo/systemjs && npm install
      - run:
          name: run-install-demo-webpack
          command: cd demo/webpack && npm install
      - run:
          name: run-install-demo-angular-cli
          command: cd demo/angular-cli && npm install
      - run:
          name: run-build-lib
          command: npm run build:lib
#      - run: FIXME
#          name: run-test
#          command: npm test
      - run:
          name: run-build-dev-demo-webpack
          command: cd demo/webpack && npm run build:dev
      - run:
          name: run-build-prod-demo-webpack
          command: cd demo/webpack && npm run build:prod
      - run:
          name: run-clean-demo-webpack
          command: cd demo/webpack && npm run clean
      - run:
          name: run-build-prod-aot-demo-webpack
          command: cd demo/webpack && npm run build:prod:aot
      - run:
          name: run-test-demo-webpack
          command: cd demo/webpack && npm test
      - run:
          name: run-build-demo-angular-cli
          command: cd demo/angular-cli && npm run build
      - run:
          name: run-build-main-angular-cli
          command: npm run build
#      - run: FIXME
#          name: run-docs
#          command: npm run docs
      - run:
          name: run-compodoc
          command: npm run compodoc
#      - run:
#          name: run-codeclimate
#          command: npm run codeclimate
#      - run:
#          name: run-coveralls
#          command: npm run coveralls
